--BEGIN TRANSACTION;

CREATE TABLE APLMZD
(MODEL          VARCHAR2(25) NOT NULL,
 YEAR       VARCHAR2(4) NOT NULL,
 DESCRIPTION    VARCHAR2(51),
 LITRES         VARCHAR2(4),
 ENGINE_TYPE    VARCHAR2(3),
 CUBIC_INCHES   VARCHAR2(6),
 RLINK          NUMBER(4),
 PRIMARY KEY    (MODEL, YEAR, DESCRIPTION, LITRES, ENGINE_TYPE, CUBIC_INCHES),
 FOREIGN KEY    (RLINK) REFERENCES RADCRX);


INSERT INTO APLMZD VALUES ('626', '82', 'M/T', '2.0', 'L4', 'NA', 931);
INSERT INTO APLMZD VALUES ('GLC (FWD)', '82', 'M/T', '1.5', 'L4', 'NA', 932);
INSERT INTO APLMZD VALUES ('GLC WAGON', '82', 'NA', '1.5', 'L4', 'NA', 665);
INSERT INTO APLMZD VALUES ('RX7', '82', 'A/T', 'NA', 'ROT', 'NA', 665);
INSERT INTO APLMZD VALUES ('RX7', '82', 'M/T', 'NA', 'ROT', 'NA', 935);
INSERT INTO APLMZD VALUES ('626', '81', 'M/T', '2.0', 'L4', 'NA', 931);
INSERT INTO APLMZD VALUES ('GLC (FWD)', '81', 'M/T', '1.5', 'L4', 'NA', 932);
INSERT INTO APLMZD VALUES ('GLC WAGON', '81', 'NA', '1.5', 'L4', 'NA', 665);
INSERT INTO APLMZD VALUES ('RX7', '81', 'A/T', 'NA', 'ROT', 'NA', 665);
INSERT INTO APLMZD VALUES ('RX7', '81', 'M/T', 'NA', 'ROT', 'NA', 935);
INSERT INTO APLMZD VALUES ('626', '80', 'M/T', '2.0', 'L4', 'NA', 931);
INSERT INTO APLMZD VALUES ('GLC WAGON', '80', 'NA', '1.4', 'L4', 'NA', 665);
INSERT INTO APLMZD VALUES ('RX7', '80', 'A/T', 'NA', 'ROT', 'NA', 665);
INSERT INTO APLMZD VALUES ('RX7', '80', 'M/T', 'NA', 'ROT', 'NA', 935);
INSERT INTO APLMZD VALUES ('626', '79', 'M/T', '2.0', 'L4', 'NA', 931);
INSERT INTO APLMZD VALUES ('GLC', '79', 'NA', '1.3', 'L4', 'NA', 665);
INSERT INTO APLMZD VALUES ('GLC', '79', 'NA', '1.4', 'L4', 'NA', 665);
INSERT INTO APLMZD VALUES ('RX7', '79', 'A/T', 'NA', 'ROT', 'NA', 665);
INSERT INTO APLMZD VALUES ('RX7', '79', 'M/T', 'NA', 'ROT', 'NA', 935);

COMMIT;
