--BEGIN TRANSACTION;

--  Creates table for Porsche

CREATE TABLE APLPOR
(MODEL      VARCHAR2(25)    NOT NULL,
 YEAR       VARCHAR2(4) NOT NULL,
 DESCRIPTION    VARCHAR2(51),
 LITRES     VARCHAR2(4),
 ENGINE_TYPE    VARCHAR2(3),
 CUBIC_INCHES   VARCHAR2(6),
 RLINK      NUMBER(4),
 PRIMARY KEY    (MODEL, YEAR, DESCRIPTION, LITRES, ENGINE_TYPE, CUBIC_INCHES),
 FOREIGN KEY    (RLINK) REFERENCES RADCRX);


INSERT INTO APLPOR VALUES ('928', '85', 'NA', 'NA', 'ALL', 'NA', 665);

COMMIT;

--  End of Porsche
