--BEGIN TRANSACTION;

--  Creates table for Renault

CREATE TABLE APLREN
(MODEL      VARCHAR2(25)    NOT NULL,
 YEAR       VARCHAR2(4) NOT NULL,
 DESCRIPTION    VARCHAR2(51),
 LITRES     VARCHAR2(4),
 ENGINE_TYPE    VARCHAR2(3),
 CUBIC_INCHES   VARCHAR2(6),
 RLINK      NUMBER(4),
 PRIMARY KEY    (MODEL, YEAR, DESCRIPTION, LITRES, ENGINE_TYPE, CUBIC_INCHES),
 FOREIGN KEY    (RLINK) REFERENCES RADCRX);


INSERT INTO APLREN VALUES ('LE CAR', '82', 'REPLACES 16 3/4" CORE ONLY, M/T', '1.4', 'L4', 'NA', 5826);
INSERT INTO APLREN VALUES ('LE CAR', '81', 'REPLACES 16 3/4" CORE ONLY, M/T', '1.4', 'L4', 'NA', 5826);
INSERT INTO APLREN VALUES ('LE CAR', '79', 'REPLACES 16 3/4" CORE ONLY, M/T', '1.3', 'L4', 'NA', 5828);

COMMIT;

--  End of Renault
