--BEGIN TRANSACTION;

CREATE TABLE APLUPS
(MODEL      VARCHAR2(25)    NOT NULL,
 YEAR       VARCHAR2(4) NOT NULL,
 DESCRIPTION    VARCHAR2(51),
 LITRES     VARCHAR2(4),
 ENGINE_TYPE    VARCHAR2(3),
 CUBIC_INCHES   VARCHAR2(6),
 RLINK      NUMBER(4),
 PRIMARY KEY    (MODEL),
 FOREIGN KEY    (RLINK) REFERENCES RADCRX);


INSERT INTO APLUPS VALUES ('GM VAN (CHASSIS)', 'NA', 'NA', 'NA', 'ALL', 'NA', 6056);

COMMIT;
