-- drop all the tables first
SET TERMOUT OFF;

DROP TABLE RDIMDAN;
DROP TABLE RDIMMOD;
DROP TABLE RDIMARS;
DROP TABLE APLOLD;
DROP TABLE APLGMC;
DROP TABLE APLFOR;
DROP TABLE APLTOY;
DROP TABLE APLSAB;
DROP TABLE APLSUB;
DROP TABLE APLVOL;
DROP TABLE APLBUK;
DROP TABLE APLMZD;
DROP TABLE APLCAD;
DROP TABLE APLUPS;
DROP TABLE APLCRY;
DROP TABLE APLINT;
DROP TABLE APLISU;
DROP TABLE APLLIN;
DROP TABLE APLREN;
DROP TABLE APLFDT;
DROP TABLE APLPOR;
DROP TABLE RDIMBEH;
DROP TABLE APLCHE;
DROP TABLE RADCRX;

SET TERMOUT ON;
PROMPT All tables dropped.;