
package local_time;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LocalTimeSoap", targetNamespace = "http://www.ripedev.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalTimeSoap {


    /**
     * Returns local time for a given zip code.
     * 
     * @param zipCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LocalTimeByZipCode", action = "http://www.ripedev.com/LocalTimeByZipCode")
    @WebResult(name = "LocalTimeByZipCodeResult", targetNamespace = "http://www.ripedev.com/")
    @RequestWrapper(localName = "LocalTimeByZipCode", targetNamespace = "http://www.ripedev.com/", className = "com.ripedev.LocalTimeByZipCode")
    @ResponseWrapper(localName = "LocalTimeByZipCodeResponse", targetNamespace = "http://www.ripedev.com/", className = "com.ripedev.LocalTimeByZipCodeResponse")
    public String localTimeByZipCode(
        @WebParam(name = "ZipCode", targetNamespace = "http://www.ripedev.com/")
        String zipCode);

}
