
package local_time;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Provides local time for the supplied zip code
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LocalTime", targetNamespace = "http://www.ripedev.com/", wsdlLocation = "http://www.ripedevelopment.com/webservices/LocalTime.asmx?wsdl=0")
public class LocalTime
    extends Service
{

    private final static URL LOCALTIME_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(local_time.LocalTime.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = local_time.LocalTime.class.getResource(".");
            url = new URL(baseUrl, "http://www.ripedevelopment.com/webservices/LocalTime.asmx?wsdl=0");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.ripedevelopment.com/webservices/LocalTime.asmx?wsdl=0', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOCALTIME_WSDL_LOCATION = url;
    }

    public LocalTime(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocalTime() {
        super(LOCALTIME_WSDL_LOCATION, new QName("http://www.ripedev.com/", "LocalTime"));
    }

    /**
     * 
     * @return
     *     returns LocalTimeSoap
     */
    @WebEndpoint(name = "LocalTimeSoap")
    public LocalTimeSoap getLocalTimeSoap() {
        return super.getPort(new QName("http://www.ripedev.com/", "LocalTimeSoap"), LocalTimeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalTimeSoap
     */
    @WebEndpoint(name = "LocalTimeSoap")
    public LocalTimeSoap getLocalTimeSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ripedev.com/", "LocalTimeSoap"), LocalTimeSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns LocalTimeSoap12
     */
    @WebEndpoint(name = "LocalTimeSoap12")
    public LocalTimeSoap12 getLocalTimeSoap12() {
        return super.getPort(new QName("http://www.ripedev.com/", "LocalTimeSoap12"), LocalTimeSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalTimeSoap12
     */
    @WebEndpoint(name = "LocalTimeSoap12")
    public LocalTimeSoap12 getLocalTimeSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ripedev.com/", "LocalTimeSoap12"), LocalTimeSoap12.class, features);
    }

    /**
     * 
     * @return
     *     returns LocalTimeHttpGet
     */
    @WebEndpoint(name = "LocalTimeHttpGet")
    public LocalTimeHttpGet getLocalTimeHttpGet() {
        return super.getPort(new QName("http://www.ripedev.com/", "LocalTimeHttpGet"), LocalTimeHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalTimeHttpGet
     */
    @WebEndpoint(name = "LocalTimeHttpGet")
    public LocalTimeHttpGet getLocalTimeHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ripedev.com/", "LocalTimeHttpGet"), LocalTimeHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns LocalTimeHttpPost
     */
    @WebEndpoint(name = "LocalTimeHttpPost")
    public LocalTimeHttpPost getLocalTimeHttpPost() {
        return super.getPort(new QName("http://www.ripedev.com/", "LocalTimeHttpPost"), LocalTimeHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalTimeHttpPost
     */
    @WebEndpoint(name = "LocalTimeHttpPost")
    public LocalTimeHttpPost getLocalTimeHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ripedev.com/", "LocalTimeHttpPost"), LocalTimeHttpPost.class, features);
    }

}
